swagger: "2.0"
info:
  version: "0.0.0"
  title: "RATES API"
host: "localhost:8002"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"

paths:
  # /upload:
  #   get:
  #     tags:
  #     - "Upload"
  #     description: "upload report and log to build machine"
  #     operationId: "upload"
  #     responses: 
  #       200:
  #         description: "Successful response"
  #     x-swagger-router-controller: "Upload"

  /ping:
    get:
      tags:
      - "Ping"
      description: "check the web service still alive"
      operationId: "pingGet"
      responses:
        200:
          description: "Successful response"
      x-swagger-router-controller: "Ping"

  /runTest:
    get:
      tags:
        - "Test"
      description: "run test"
      operationId: "runTest"
      parameters: 
      - name: branch
        in: query
        description: "branch"
        required: false
        type: "string"
      responses:
        200:
          description: "Successful response"
      x-swagger-router-controller: "RunTest"
  
  /getReport/{uuid}:
    get:
      tags:
        - "Report"
      description: "get report"
      operationId: "getReport"
      parameters:
      - name: uuid
        in: path
        description: "uuid"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
      x-swagger-router-controller: "GetReport"

  /getLog/{uuid}:
    get:
      tags:
        - "Log"
      description: "get log"
      operationId: "getLog"
      parameters:
      - name: uuid
        in: path
        description: "uuid"
        required: true
        type: "string"
      responses:
        200:
          description: "Successful response"
      x-swagger-router-controller: "GetLog"